# Generated by Django 3.1.4 on 2020-12-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmodel',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
