# Generated by Django 3.1.4 on 2021-09-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0003_auto_20210926_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitmodel',
            name='time',
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('hour', '時間'), ('minutes', '分')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='time_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='frequency',
            field=models.CharField(blank=True, choices=[('year', '1年'), ('month', '1ヶ月'), ('week', '1週間'), ('day', '1日')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='good_or_bad',
            field=models.CharField(blank=True, choices=[('good', '良い習慣'), ('bad', '悪い習慣'), ('normal', '日常習慣')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
