# Generated by Django 3.1.4 on 2021-12-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0004_auto_20210927_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='frequency',
            field=models.CharField(blank=True, choices=[('month', '1ヶ月'), ('week', '1週間'), ('day', '1日')], max_length=10, null=True),
        ),
    ]
